"""Bootstrap the ~30M-parameter network and gate it against the incumbent.

A fresh 256x24 residual network (value hidden 512, ~29.7M parameters) trains
on the full clean replay window generated by the 3.7M-parameter lineage, then
must beat the round-22 incumbent in the standard 60-game parallel arena to
take over best.pt. Same rules, same gate; only the candidate's architecture
changes. Zero human data throughout — the window is entirely self-play.
"""

from dataclasses import replace

from wallzero.campaign import run_training_round
from wallzero.network import NetworkConfig
from wallzero.pipeline import preset

_base = preset("colab")

run_training_round(
    "/content/wallzero-output",
    replace(
        _base,
        replay_window=24_000,
        arena=replace(_base.arena, promotion_threshold=0.5),
        arena_mcts=replace(_base.arena_mcts, simulations=256, leaf_batch=8),
    ),
    training_steps=4_000,
    arena_games=60,
    arena_workers=10,
    candidate_network=NetworkConfig(channels=256, blocks=24, value_hidden=512),
    device_name="cuda",
)
